version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]
    groups:
      minor-and-patch:
        update-types: [minor, patch]
        exclude-patterns:
          - "@shadcn/lint"
          - drizzle-kit
          - drizzle-orm
          - prettier-plugin-tailwindcss
          - server-only
          - sharp

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci
      include: scope
    groups:
      minor-and-patch:
        update-types: [minor, patch]
